weekfour/src/java/au/edu/uts/aip/advice/QuestionController.java
package au.edu.uts.aip.advice;

import javax.inject.*;
import javax.enterprise.context.*;

@Named
@RequestScoped
public class QuestionController {

    public String doSuggestion() {
        if (Math.random() < 0.5) {
            return "morecats";
        } else {
            return "newgown";
        }
    }

}

weekfour/src/java/au/edu/uts/aip/waitinglist/GroupController.java
package au.edu.uts.aip.waitinglist;

import java.io.*;
import javax.enterprise.context.*;
import javax.inject.*;

@Named
@RequestScoped
public class GroupController implements Serializable {

    private Group group = new Group();

    public Group getGroup() {
        return group;
    }
    
    public String saveAsNew() {
        WaitingListDatabase.create(group);
        
        return "waitinglist";
    }
    
    public void loadGroup(int index) {
        group = WaitingListDatabase.read(index);
    }
    
    public String saveChanges() {
        WaitingListDatabase.update(group);
        
        return "waitinglist";
    }
    
    public String deleteGroup() {
        WaitingListDatabase.delete(group.getId());
        
        return "waitinglist";
    }

}

weekfour/src/java/au/edu/uts/aip/waitinglist/WaitingListController.java
package au.edu.uts.aip.waitinglist;

import java.io.*;
import java.util.*;
import javax.enterprise.context.*;
import javax.faces.context.*;
import javax.inject.*;

@Named
@RequestScoped
public class WaitingListController implements Serializable {

    public Collection<Group> getGroups() {
        return WaitingListDatabase.findAll();
    }

}

weekfour/web/deletegroup.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <f:metadata>
        <f:viewAction action="#{groupController.loadGroup(param.index)}"/>
    </f:metadata>
    <h:head>
        <title>Waiting List</title>
    </h:head>
    <h:body>
        <h1>Edit Group</h1>
        <h:form>
            <p>
                <label>Group Name:
                    <h:outputText value="#{groupController.group.name}"/>
                </label>
            </p>
            <p>
                <label>Group Size:
                    <h:outputText value="#{groupController.group.size}"/>
                </label>
            </p>
            <p>
                <h:inputHidden value="#{groupController.group.id}"/>
                <h:button value="Cancel" outcome="waitinglist"/>
                <h:commandButton value="Confirm" action="#{groupController.deleteGroup}"/>
            </p>
        </h:form>
    </h:body>
</html>

weekfour/web/editgroup.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <f:metadata>
        <f:viewAction action="#{groupController.loadGroup(param.index)}"/>
    </f:metadata>
    <h:head>
        <title>Waiting List</title>
    </h:head>
    <h:body>
        <h1>Edit Group</h1>
        <h:form>
            <p>
                <label>Group Name:
                    <h:inputText id="name" value="#{groupController.group.name}" validatorMessage="You must enter a name." />
                    <h:message for="name"/>
                </label>
            </p>
            <p>
                <label>Group Size:
                    <h:inputText id="size" value="#{groupController.group.size}" validatorMessage="Please enter a group size between 1 and 20." converterMessage="You must enter a valid number."/>
                    <h:message for="size"/>
                </label>
            </p>
            <p>
                <h:inputHidden value="#{groupController.group.id}"/>
                <h:button value="Cancel" outcome="waitinglist"/>
                <h:commandButton value="Save" action="#{groupController.saveChanges}"/>
            </p>
        </h:form>
    </h:body>
</html>

weekfour/web/newgroup.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Waiting List</title>
    </h:head>
    <h:body>
        <h1>New Group</h1>
        <h:form>
            <p>
                <label>Group Name:
                    <h:inputText id="name" value="#{groupController.group.name}" validatorMessage="You must enter a name."/>
                    <h:message for="name"/>
                </label>
            </p>
            <p>
                <label>Group Size:
                    <h:inputText id="size" value="#{groupController.group.size}" validatorMessage="Please enter a group size between 1 and 20." converterMessage="You must enter a valid number."/>
                    <h:message for="size"/>
                </label>
            </p>
            <p>
                <h:commandButton value="Save" action="#{groupController.saveAsNew}"/>
            </p>
        </h:form>
    </h:body>
</html>

weekfour/web/practice/good.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Bad Advice</title>
    </h:head>
    <h:body>
        <p>It is good that you're happy.</p>
    </h:body>
</html>

weekfour/web/practice/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        Hello from Facelets
    </h:body>
</html>

weekfour/web/practice/morecats.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Bad Advice</title>
    </h:head>
    <h:body>
        <p>Get more cats.</p>
        <p>
            <h:button value="Ok" outcome="question"/>
        </p>
    </h:body>
</html>

weekfour/web/practice/newgown.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Bad Advice</title>
    </h:head>
    <h:body>
        <p>Buy a new dressing gown.</p>
        <p>
            <h:button value="Ok" outcome="question"/>
        </p>
    </h:body>
</html>

weekfour/web/practice/question.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Bad Advice</title>
    </h:head>
    <h:body>
        <h:form>
            <p>Are you happy?</p>
            <p>
                <h:button value="Yes" outcome="good"/>
                <h:commandButton value="No" action="#{questionController.doSuggestion}"/>
            </p>
        </h:form>
    </h:body>
</html>

weekfour/web/waitinglist.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Waiting List</title>
    </h:head>
    <h:body>
        <h:dataTable var="group"  value="#{waitingListController.groups}">
            <h:column>
                <f:facet name="header">
                    Group Name
                </f:facet>
                <h:outputText value="#{group.name}"/>
            </h:column>
            <h:column>
                <f:facet name="header">
                    Group Size
                </f:facet>
                <h:outputText value="#{group.size}"/>
            </h:column>
            <h:column>
                <h:link value="Edit" outcome="editgroup">
                    <f:param name="index" value="#{group.id}"/>
                </h:link>
            </h:column>
            <h:column>
                <h:link value="Delete" outcome="deletegroup">
                    <f:param name="index" value="#{group.id}"/>
                </h:link>
            </h:column>
        </h:dataTable>
        <h:link value="New Group" outcome="newgroup" />
    </h:body>
</html>