weekfivec/src/main/java/au/edu/uts/aip/accounts/AccountController.java
package au.edu.uts.aip.accounts;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.sql.DataSource;

@Named
@RequestScoped
public class AccountController {

    public ArrayList<AccountDTO> getAllUsers() throws NamingException {
        AccountDAO accountDAO = new AccountDAO();
        return accountDAO.findAll();
    }

    public void listUsers() throws NamingException {
        Logger log = Logger.getLogger(this.getClass().getName());
        DataSource ds = (DataSource) InitialContext.doLookup("jdbc/aip");

        try (Connection conn = ds.getConnection();
             Statement statement = conn.createStatement();
             ResultSet result = statement.executeQuery("select * from account")) {

            log.info("The accounts table contains:");

            ResultSetMetaData resultMeta = result.getMetaData();
            int numberOfColumns = resultMeta.getColumnCount();

            while (result.next()) {
                String output = "";
                log.info("Test");

                for (int i = 1; i <= numberOfColumns; i++) {
                    String columnName = resultMeta.getColumnName(i);
                    String columnValue = result.getString(i);
                    output += String.format("%s = %s", columnName, columnValue);
                    if (i != numberOfColumns) output += ", ";
                }

                log.info(output);
            }

        } catch (SQLException ex) {
            Logger.getLogger(AccountController.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}

weekfivec/web/accounts.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
    <title>Facelet Title</title>
</h:head>
<h:body>
    <h:form>
        <h:messages/>
        <h:dataTable var="row" value="#{accountController.allUsers}">
            <h:column>
                <f:facet name="header">
                    Username
                </f:facet>
                <h:outputText value="#{row.username}"/>
            </h:column>
            <h:column>
                <f:facet name="header">
                    Password
                </f:facet>
                <h:outputText value="#{row.password}"/>
            </h:column>
            <h:column>
                <f:facet name="header">
                    Full Name
                </f:facet>
                <h:outputText value="#{row.fullname}"/>
            </h:column>
            <h:column>
                <f:facet name="header">
                    Email
                </f:facet>
                <h:outputText value="#{row.email}"/>
            </h:column>
            <h:column>
                <f:facet name="header">
                    Date of Birth
                </f:facet>
                <h:outputText value="#{row.dob}"/>
            </h:column>
        </h:dataTable>
    </h:form>
</h:body>
</html>

weekfivec/web/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
   <f:view>
      <h:outputLabel value="Hello, world"/>
   </f:view>
</html>